# Generated by Django 5.1.3 on 2024-11-26 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='db_akses',
            fields=[
                ('id_akses', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('nama_akses', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='db_staff',
            fields=[
                ('id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('id_akses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cluster.db_akses')),
            ],
        ),
    ]
