# Generated by Django 5.1.3 on 2024-11-26 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='db_akses',
            new_name='tb_akses',
        ),
        migrations.RenameModel(
            old_name='db_staff',
            new_name='tb_staff',
        ),
    ]
