# Generated by Django 5.1.3 on 2024-11-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0002_rename_db_akses_tb_akses_rename_db_staff_tb_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_akses',
            name='id_akses',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tb_staff',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
