# Generated by Django 5.1.3 on 2024-11-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0003_alter_tb_akses_id_akses_alter_tb_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_staff',
            name='username',
            field=models.CharField(max_length=25),
        ),
    ]
