# Generated by Django 5.1.3 on 2024-11-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0004_alter_tb_staff_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_data',
            fields=[
                ('id_data', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_penyakit', models.CharField(max_length=100)),
                ('tanggal_input', models.DateField()),
                ('r1', models.IntegerField()),
                ('r2', models.IntegerField()),
                ('r3', models.IntegerField()),
                ('r4', models.IntegerField()),
                ('r5', models.IntegerField()),
                ('r6', models.IntegerField()),
                ('r7', models.IntegerField()),
                ('r8', models.IntegerField()),
                ('r9', models.IntegerField()),
                ('r10', models.IntegerField()),
                ('r11', models.IntegerField()),
                ('r12', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
