# Generated by Django 5.1.3 on 2024-11-28 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0006_tb_staff_email_tb_staff_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tb_staff',
        ),
    ]
