# Generated by Django 5.1.3 on 2024-11-28 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0007_delete_tb_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(default=None, max_length=50)),
                ('last_name', models.CharField(default=None, max_length=50)),
                ('email', models.EmailField(default=None, max_length=100, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('id_akses', models.ForeignKey(choices=[(21, 'Dokter/Apoteker'), (22, 'Staff Administrasi')], on_delete=django.db.models.deletion.CASCADE, to='cluster.tb_akses')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
