# Generated by Django 5.1.3 on 2024-11-28 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0008_tb_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tb_staff',
        ),
    ]
