# Generated by Django 5.1.3 on 2024-11-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0010_tb_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_staff',
            name='id_akses',
            field=models.PositiveSmallIntegerField(choices=[(21, 'Dokter/Apoteker'), (22, 'Staff Administrasi')]),
        ),
    ]
