# Generated by Django 5.1.3 on 2024-11-29 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0015_alter_tb_staff_id_akses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_staff',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='tb_staff',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='tb_staff',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='tb_staff',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='tb_staff',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='tb_staff',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='tb_staff',
            name='id_akses',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cluster.tb_akses'),
        ),
        migrations.AlterField(
            model_name='tb_staff',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
