# Generated by Django 5.1.3 on 2024-12-06 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0016_remove_tb_staff_first_name_remove_tb_staff_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_jenis_penyakit',
            fields=[
                ('id_jenis_penyakit', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_jenis_penyakit', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tb_penyakit',
            fields=[
                ('id_penyakit', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_penyakit', models.CharField(max_length=255)),
                ('id_jenis_penyakit', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cluster.tb_jenis_penyakit')),
            ],
        ),
    ]
