# Generated by Django 5.1.3 on 2024-12-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0017_tb_jenis_penyakit_tb_penyakit'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_hasil_cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_penyakit', models.CharField(max_length=255)),
                ('tanggal', models.DateField()),
                ('hasil_klasifikasi', models.CharField(max_length=50)),
            ],
        ),
    ]
