# Generated by Django 5.1.3 on 2024-12-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0018_tb_hasil_cluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_staff',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
