# Generated by Django 5.1.3 on 2024-12-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0019_alter_tb_staff_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_hasil_prediksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_penyakit', models.CharField(max_length=255)),
                ('tanggal', models.DateField()),
                ('hasil_prediksi', models.CharField(max_length=50)),
            ],
        ),
    ]
